import { Contract } from './types'

function daysFrom(dateStr: string): number {
  const today = new Date('2026-06-16')
  const target = new Date(dateStr)
  return Math.round((target.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
}

export const mockContracts: Contract[] = [
  // Contract 1: Office Lease Barcelona
  {
    id: 'c001',
    name: 'Office Lease – Barcelona HQ',
    counterparty: 'Inmobiliaria Sagrada Partners SL',
    type: 'Lease',
    status: 'active',
    value: 42000,
    uploadDate: '2024-03-15',
    effectiveDate: '2024-03-01',
    expiryDate: '2027-02-28',
    riskScore: 72,
    riskBreakdown: [
      { category: 'Auto-Renewal', count: 1, severity: 'high' },
      { category: 'Notice Requirements', count: 1, severity: 'high' },
      { category: 'Maintenance Obligations', count: 1, severity: 'medium' },
      { category: 'Governing Law', count: 1, severity: 'low' },
    ],
    clauses: [
      {
        id: 'c001-cl1',
        text: 'Unless Tenant provides written notice of non-renewal no fewer than ninety (90) calendar days prior to the Expiration Date, this Lease shall automatically renew for successive one (1) year periods under the same terms and conditions, with annual rent escalation not to exceed eight percent (8%) per annum.',
        risk: 'critical',
        category: 'Auto-Renewal',
        explanation: 'The 90-day notice window combined with an 8% escalation cap creates significant financial exposure. Missing the notice deadline (December 1, 2026) locks you in for another year at potentially €45,360.',
        suggestedRedline: 'Unless Tenant provides written notice of non-renewal no fewer than thirty (30) calendar days prior to the Expiration Date, this Lease shall automatically renew for one (1) additional year. Any rent escalation shall not exceed the lesser of three percent (3%) or the Harmonized Index of Consumer Prices (HICP) for the prior calendar year.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c001-cl2',
        text: 'Tenant shall bear sole responsibility for all maintenance, repair, and replacement of HVAC systems, plumbing fixtures, electrical panels, and structural elements within the demised premises, regardless of the cause or origin of the defect.',
        risk: 'critical',
        category: 'Maintenance Obligations',
        explanation: 'Placing structural maintenance on the tenant is unusual and creates unlimited repair liability. Standard commercial leases limit tenant responsibility to interior non-structural elements.',
        suggestedRedline: 'Tenant shall be responsible for routine maintenance of HVAC filters, light fixtures, and interior cosmetic repairs. Landlord shall bear responsibility for all structural repairs, roof, plumbing mains, and HVAC system replacements.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c001-cl3',
        text: 'This Agreement shall be governed by and construed in accordance with the laws of the Autonomous Community of Catalonia, with exclusive jurisdiction vested in the courts of Barcelona, Spain.',
        risk: 'low',
        category: 'Governing Law',
        explanation: 'Jurisdiction is appropriate given the property location. No material risk for a Barcelona-based entity.',
      },
      {
        id: 'c001-cl4',
        text: 'Landlord reserves the right to inspect the premises upon providing not less than twenty-four (24) hours prior written notice, except in cases of emergency wherein no prior notice shall be required.',
        risk: 'medium',
        category: 'Access Rights',
        explanation: 'The emergency access carve-out is standard but the 24-hour notice window is on the shorter end for commercial leases. Consider negotiating for 48–72 hours.',
        suggestedRedline: 'Landlord may inspect the premises upon providing not less than forty-eight (48) hours prior written notice, except in genuine emergency situations posing immediate risk to life or property.',
        negotiationLeverage: 'low',
      },
    ],
    keyDates: [
      {
        label: 'Action Deadline – Non-Renewal Notice',
        date: '2026-12-01',
        daysRemaining: daysFrom('2026-12-01'),
        urgency: 'warning',
        noticeRequired: 90,
        actionDeadline: '2026-12-01',
        type: 'notice',
      },
      {
        label: 'Lease Expiry',
        date: '2027-02-28',
        daysRemaining: daysFrom('2027-02-28'),
        urgency: 'normal',
        type: 'expiry',
      },
      {
        label: 'Annual Rent Review',
        date: '2026-03-01',
        daysRemaining: daysFrom('2026-03-01'),
        urgency: 'normal',
        type: 'milestone',
      },
    ],
    summary: {
      description: 'Commercial office lease for ContractWatch headquarters in Barcelona\'s Eixample district. 450 sqm open-plan space over 3 floors with dedicated server room.',
      termLength: '3 years (2024-03-01 to 2027-02-28)',
      keyObligations: [
        'Monthly rent of €3,500 payable by 5th of each month',
        'Tenant responsible for all internal maintenance including HVAC',
        '90-day written notice required for non-renewal',
        'Security deposit of €10,500 (3 months) held by Landlord',
      ],
      biggestRisk: 'Auto-renewal with 90-day notice window means the effective decision deadline is December 1, 2026 — only 168 days away. Missing this triggers another year at up to €45,360.',
      recommendedAction: 'Set calendar reminder for November 1, 2026. Begin space assessment by September 2026. Negotiate maintenance clause restructuring at next rent review.',
    },
    recurringObligations: [
      {
        id: 'c001-ro1',
        label: 'Monthly Rent Payment',
        frequency: 'monthly',
        nextDue: '2026-07-05',
        description: 'Monthly rent of €3,500 due by 5th of each month. Late payment incurs 2% penalty.',
      },
      {
        id: 'c001-ro2',
        label: 'HVAC Service Report',
        frequency: 'quarterly',
        nextDue: '2026-09-01',
        description: 'Certified HVAC maintenance report required quarterly per Clause 8.3.',
      },
    ],
  },

  // Contract 2: SaaS Project Management Tool
  {
    id: 'c002',
    name: 'ProjectFlow SaaS Subscription',
    counterparty: 'ProjectFlow Technologies Inc.',
    type: 'SaaS Subscription',
    status: 'expiring_soon',
    value: 8400,
    uploadDate: '2025-07-15',
    effectiveDate: '2025-08-01',
    expiryDate: '2026-08-01',
    riskScore: 65,
    riskBreakdown: [
      { category: 'Price Escalation', count: 1, severity: 'high' },
      { category: 'Cancellation Notice', count: 1, severity: 'high' },
      { category: 'Data Portability', count: 1, severity: 'medium' },
      { category: 'Liability Cap', count: 1, severity: 'low' },
    ],
    clauses: [
      {
        id: 'c002-cl1',
        text: 'Vendor reserves the right to adjust pricing at any time upon thirty (30) days written notice to Customer. Customer\'s continued use of the Service after the notice period shall constitute acceptance of the revised pricing.',
        risk: 'critical',
        category: 'Price Escalation',
        explanation: 'Uncapped unilateral price increases with only 30 days notice and automatic acceptance via continued use is a significant commercial risk. Current rate is €700/month — could increase without limit.',
        suggestedRedline: 'Vendor may adjust pricing annually, effective on the renewal date, with sixty (60) days prior written notice. Any price increase shall not exceed five percent (5%) per annum. Customer may terminate without penalty if the proposed increase exceeds this cap.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c002-cl2',
        text: 'Customer must provide written cancellation notice no fewer than thirty (30) calendar days prior to the Renewal Date. Failure to provide timely notice shall result in automatic renewal for a successive twelve (12) month term at the then-current pricing.',
        risk: 'critical',
        category: 'Cancellation Notice',
        explanation: 'With expiry on August 1, 2026, the cancellation deadline is July 2, 2026 — only 16 days from today. Immediate action required to avoid unwanted renewal at potentially increased pricing.',
        suggestedRedline: 'Customer may cancel at any time with fourteen (14) days written notice, effective at the end of the then-current billing period.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c002-cl3',
        text: 'Upon termination or expiration of this Agreement, Vendor will make Customer Data available for export in CSV format for a period of thirty (30) days. Thereafter, all Customer Data will be permanently deleted.',
        risk: 'medium',
        category: 'Data Portability',
        explanation: '30-day export window post-termination is tight for an enterprise with years of project data. Ensure data export is initiated immediately upon any termination.',
        suggestedRedline: 'Upon termination, Vendor will provide Customer Data export in industry-standard formats (CSV, JSON, XML) for a minimum of ninety (90) days at no additional charge.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c002-cl4',
        text: 'Vendor\'s total liability shall not exceed the fees paid by Customer in the three (3) months preceding the claim.',
        risk: 'low',
        category: 'Liability Cap',
        explanation: 'Standard SaaS liability cap at 3 months of fees (€2,100). Appropriate for this contract size.',
      },
    ],
    keyDates: [
      {
        label: 'CRITICAL: Cancellation Deadline',
        date: '2026-07-02',
        daysRemaining: daysFrom('2026-07-02'),
        urgency: 'critical',
        noticeRequired: 30,
        actionDeadline: '2026-07-02',
        type: 'cancellation',
      },
      {
        label: 'Subscription Renewal / Expiry',
        date: '2026-08-01',
        daysRemaining: daysFrom('2026-08-01'),
        urgency: 'critical',
        type: 'renewal',
      },
    ],
    summary: {
      description: 'Annual SaaS subscription for ProjectFlow project management platform. 15 user seats, includes Gantt, time tracking, and client portal modules.',
      termLength: '12 months (2025-08-01 to 2026-08-01)',
      keyObligations: [
        'Annual payment of €8,400 (or €700/month)',
        '30-day cancellation notice before August 1, 2026 (deadline: July 2)',
        'Maximum 15 user seats — overage charged at €65/seat/month',
        'Maintain valid payment method on file',
      ],
      biggestRisk: 'Cancellation deadline is July 2, 2026 — 16 days away. If no action is taken, the contract auto-renews for 12 months at unilaterally adjustable pricing.',
      recommendedAction: 'URGENT: Decide by July 2, 2026 whether to renew or cancel. Send written cancellation notice today if not renewing. If renewing, negotiate price escalation cap before renewal.',
    },
    recurringObligations: [
      {
        id: 'c002-ro1',
        label: 'Annual License Fee',
        frequency: 'annual',
        nextDue: '2026-08-01',
        description: 'Annual SaaS fee of €8,400 due on renewal date.',
      },
    ],
  },

  // Contract 3: Client NDA
  {
    id: 'c003',
    name: 'Mutual NDA – Freelance Client',
    counterparty: 'Nexus Digital Studios SL',
    type: 'NDA',
    status: 'active',
    value: 0,
    uploadDate: '2026-01-10',
    effectiveDate: '2026-01-15',
    expiryDate: '2028-01-01',
    riskScore: 12,
    riskBreakdown: [
      { category: 'Confidentiality Scope', count: 1, severity: 'low' },
      { category: 'Term & Termination', count: 1, severity: 'low' },
    ],
    clauses: [
      {
        id: 'c003-cl1',
        text: 'Each party agrees to hold in confidence and not disclose to any third party any Confidential Information received from the other party, and to use such Confidential Information solely for the purpose of evaluating and executing the Permitted Purpose.',
        risk: 'low',
        category: 'Confidentiality Scope',
        explanation: 'Standard mutual confidentiality obligation. Scope is appropriately defined and reciprocal.',
      },
      {
        id: 'c003-cl2',
        text: 'This Agreement shall remain in effect for a period of two (2) years from the Effective Date, unless earlier terminated by either party upon thirty (30) days written notice.',
        risk: 'low',
        category: 'Term & Termination',
        explanation: '2-year mutual NDA with 30-day termination right. Standard and balanced.',
      },
      {
        id: 'c003-cl3',
        text: 'Confidential Information shall not include information that: (a) is or becomes publicly known through no breach of this Agreement; (b) was rightfully known by the receiving party prior to disclosure; (c) is independently developed without use of Confidential Information.',
        risk: 'low',
        category: 'Exclusions',
        explanation: 'Standard and complete exclusions list. Protects both parties appropriately.',
      },
    ],
    keyDates: [
      {
        label: 'NDA Expiry',
        date: '2028-01-01',
        daysRemaining: daysFrom('2028-01-01'),
        urgency: 'normal',
        type: 'expiry',
      },
    ],
    summary: {
      description: 'Mutual non-disclosure agreement covering the evaluation and potential engagement with Nexus Digital Studios for a web application development project.',
      termLength: '2 years (2026-01-15 to 2028-01-01)',
      keyObligations: [
        'Keep all disclosed information strictly confidential',
        'Use information only for the Permitted Purpose',
        'Return or destroy confidential materials upon request',
      ],
      biggestRisk: 'Low risk agreement. Standard mutual NDA with balanced obligations.',
      recommendedAction: 'No action required. File for reference. Review scope if engagement expands significantly.',
    },
    recurringObligations: [],
  },

  // Contract 4: Equipment Rental
  {
    id: 'c004',
    name: 'Equipment Rental – Cameras & Workstations',
    counterparty: 'EquipPro Rentals Barcelona SL',
    type: 'Vendor Agreement',
    status: 'active',
    value: 15600,
    uploadDate: '2025-09-20',
    effectiveDate: '2025-10-01',
    expiryDate: '2026-09-30',
    riskScore: 81,
    riskBreakdown: [
      { category: 'Unlimited Liability', count: 1, severity: 'high' },
      { category: 'Equipment Damage', count: 1, severity: 'high' },
      { category: 'Indemnification', count: 1, severity: 'high' },
      { category: 'Insurance Requirements', count: 1, severity: 'medium' },
    ],
    clauses: [
      {
        id: 'c004-cl1',
        text: 'Customer shall be liable for the full replacement cost of any Equipment that is lost, stolen, damaged, or destroyed during the Rental Period, regardless of cause, including but not limited to acts of God, theft by third parties, or equipment failure. Customer\'s liability under this clause shall be unlimited.',
        risk: 'critical',
        category: 'Unlimited Liability',
        explanation: 'Unlimited liability for equipment loss regardless of cause is commercially unreasonable. Equipment fleet valued at approximately €85,000 replacement cost creates catastrophic exposure.',
        suggestedRedline: 'Customer shall be liable for Equipment damage caused by Customer\'s gross negligence or willful misconduct, up to the depreciated fair market value of the affected Equipment. Customer\'s liability shall not exceed €15,000 per incident. Normal wear and tear is excluded.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c004-cl2',
        text: 'Customer shall indemnify, defend, and hold harmless EquipPro Rentals, its officers, directors, employees, and agents from any and all claims, damages, losses, costs, and expenses (including reasonable attorney\'s fees) arising out of or related to Customer\'s use of the Equipment.',
        risk: 'critical',
        category: 'Indemnification',
        explanation: 'Broad one-sided indemnification without any corresponding obligation from the vendor creates significant legal exposure for third-party claims.',
        suggestedRedline: 'Each party shall indemnify the other for claims arising from that party\'s own negligence, willful misconduct, or breach of this Agreement. Customer indemnification shall not apply to claims arising from Equipment defects or Vendor\'s own negligence.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c004-cl3',
        text: 'Customer must maintain comprehensive general liability insurance of not less than €2,000,000 per occurrence and provide Vendor with a certificate of insurance naming Vendor as additional insured within five (5) business days of Agreement execution.',
        risk: 'medium',
        category: 'Insurance Requirements',
        explanation: 'Insurance requirement is reasonable but the additional insured requirement should be reviewed with your insurer to confirm coverage.',
        negotiationLeverage: 'low',
      },
      {
        id: 'c004-cl4',
        text: 'Equipment rental fees are due on the first business day of each calendar month. Late payments shall incur interest at the rate of 1.5% per month (18% per annum) compounded monthly.',
        risk: 'medium',
        category: 'Payment Terms',
        explanation: '18% annual interest on late payments is above typical commercial rates. Consider negotiating to prime rate + 2%.',
        suggestedRedline: 'Equipment rental fees are due within fifteen (15) days of invoice. Late payments shall incur interest at the ECB base rate plus two percent (2%) per annum.',
        negotiationLeverage: 'medium',
      },
    ],
    keyDates: [
      {
        label: 'Contract Expiry',
        date: '2026-09-30',
        daysRemaining: daysFrom('2026-09-30'),
        urgency: 'warning',
        type: 'expiry',
      },
      {
        label: 'Mid-Term Inventory Review',
        date: '2026-04-01',
        daysRemaining: daysFrom('2026-04-01'),
        urgency: 'normal',
        type: 'milestone',
      },
    ],
    summary: {
      description: 'Annual equipment rental covering 4 cinema-grade cameras, 6 professional workstations, and associated accessories for production work.',
      termLength: '12 months (2025-10-01 to 2026-09-30)',
      keyObligations: [
        'Monthly rental fee of €1,300 due on first business day',
        'Maintain €2M liability insurance with Vendor as additional insured',
        'Report any equipment damage within 24 hours',
        'Return all equipment in original condition (normal wear excepted)',
      ],
      biggestRisk: 'Unlimited liability clause exposes the company to up to €85,000 replacement cost for equipment loss, regardless of fault. This is the most dangerous clause in the portfolio.',
      recommendedAction: 'Engage Vendor immediately to negotiate liability cap. Verify current insurance covers equipment rental. Begin seeking alternative vendors if Vendor refuses to amend.',
    },
    recurringObligations: [
      {
        id: 'c004-ro1',
        label: 'Monthly Equipment Rental Fee',
        frequency: 'monthly',
        nextDue: '2026-07-01',
        description: 'Monthly rental payment of €1,300 due first business day of month.',
      },
    ],
  },

  // Contract 5: Adobe Creative Cloud License
  {
    id: 'c005',
    name: 'Adobe Creative Cloud – Team License',
    counterparty: 'Adobe Systems Inc.',
    type: 'Licensing',
    status: 'active',
    value: 6240,
    uploadDate: '2025-12-28',
    effectiveDate: '2026-01-01',
    expiryDate: '2026-12-31',
    riskScore: 38,
    riskBreakdown: [
      { category: 'Seat-Based Pricing', count: 1, severity: 'medium' },
      { category: 'Usage Data', count: 1, severity: 'low' },
      { category: 'Software Updates', count: 1, severity: 'low' },
    ],
    clauses: [
      {
        id: 'c005-cl1',
        text: 'License fees are calculated based on the number of Named Users designated by Customer. Customer may add additional Named User licenses at the then-current per-seat rate. Reduction of Named User count is only permitted at the annual renewal date.',
        risk: 'medium',
        category: 'Seat-Based Pricing',
        explanation: 'Cannot reduce seats mid-term, only increase. If team shrinks, you continue paying for unused seats until December 31, 2026.',
        suggestedRedline: 'Customer may adjust Named User count (up or down) on a quarterly basis with thirty (30) days notice. Pro-rated credits apply for seat reductions.',
        negotiationLeverage: 'low',
      },
      {
        id: 'c005-cl2',
        text: 'Adobe may collect and use aggregated, anonymized data regarding Customer\'s usage of the Software to improve Adobe products and services.',
        risk: 'low',
        category: 'Usage Data',
        explanation: 'Standard SaaS telemetry clause. Anonymized and aggregated — acceptable for most organizations.',
      },
      {
        id: 'c005-cl3',
        text: 'Adobe reserves the right to modify, update, or discontinue features of the Software at its discretion with reasonable notice to Customer.',
        risk: 'low',
        category: 'Software Updates',
        explanation: 'Standard feature change clause. "Reasonable notice" is vague but typical for consumer-grade SaaS agreements.',
      },
    ],
    keyDates: [
      {
        label: 'Annual Renewal',
        date: '2026-12-31',
        daysRemaining: daysFrom('2026-12-31'),
        urgency: 'normal',
        type: 'renewal',
      },
      {
        label: 'Renewal Decision Deadline',
        date: '2026-12-01',
        daysRemaining: daysFrom('2026-12-01'),
        urgency: 'normal',
        type: 'notice',
      },
    ],
    summary: {
      description: 'Adobe Creative Cloud All Apps license for 8 team members, covering Photoshop, Illustrator, Premiere Pro, After Effects, and all other CC apps.',
      termLength: '12 months (2026-01-01 to 2026-12-31)',
      keyObligations: [
        'Annual fee of €6,240 prepaid',
        'Maximum 8 named user seats — cannot reduce mid-term',
        'Comply with Adobe end-user license agreement',
        'No sharing of credentials between users',
      ],
      biggestRisk: 'Seat reduction not permitted mid-term. If headcount drops, unused licenses are still charged.',
      recommendedAction: 'Review team headcount before December renewal. Assess whether all 8 seats are actively used. Consider negotiating quarterly seat flexibility at renewal.',
    },
    recurringObligations: [
      {
        id: 'c005-ro1',
        label: 'Annual License Renewal',
        frequency: 'annual',
        nextDue: '2026-12-31',
        description: 'Annual Creative Cloud team license renewal.',
      },
    ],
  },

  // Contract 6: Marketing Agency Retainer
  {
    id: 'c006',
    name: 'Marketing Retainer – Digital Growth Agency',
    counterparty: 'Amplify Digital SL',
    type: 'Retainer',
    status: 'active',
    value: 36000,
    uploadDate: '2025-11-01',
    effectiveDate: '2025-11-01',
    expiryDate: '2026-10-31',
    riskScore: 74,
    riskBreakdown: [
      { category: 'Termination Rights', count: 1, severity: 'high' },
      { category: 'IP Ownership', count: 1, severity: 'high' },
      { category: 'Performance Standards', count: 1, severity: 'medium' },
      { category: 'Exclusivity', count: 1, severity: 'medium' },
    ],
    clauses: [
      {
        id: 'c006-cl1',
        text: 'Vendor may terminate this Agreement at any time upon thirty (30) days written notice. Client may only terminate this Agreement for cause, defined solely as Vendor\'s material breach that remains uncured for sixty (60) days following written notice. Client may not terminate for convenience.',
        risk: 'critical',
        category: 'Termination Rights',
        explanation: 'Critically unbalanced termination clause: Vendor can exit in 30 days, but Client is locked in unless proving a 60-day uncured material breach. No termination for convenience for Client.',
        suggestedRedline: 'Either party may terminate this Agreement for convenience upon sixty (60) days written notice. Either party may terminate immediately upon the other party\'s material breach, subject to a thirty (30) day cure period.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c006-cl2',
        text: 'All creative works, campaigns, content, and deliverables produced by Vendor under this Agreement shall remain the exclusive intellectual property of Vendor. Client is granted a non-exclusive, revocable license to use such works only during the term of this Agreement.',
        risk: 'critical',
        category: 'IP Ownership',
        explanation: 'Retaining IP ownership in the vendor is highly unusual and dangerous. All content, campaigns, and brand assets created become unusable if the relationship ends. Client loses all marketing materials upon termination.',
        suggestedRedline: 'All creative works and deliverables created specifically for Client and paid for by Client shall be considered works-for-hire and shall vest exclusively in Client upon full payment. Vendor retains rights to pre-existing tools, templates, and methodologies.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c006-cl3',
        text: 'Vendor will use commercially reasonable efforts to achieve mutually agreed KPIs. Failure to achieve KPIs shall not constitute a breach or grounds for termination.',
        risk: 'medium',
        category: 'Performance Standards',
        explanation: '"Commercially reasonable efforts" without defined consequences for KPI failure means there is no meaningful performance accountability.',
        suggestedRedline: 'Vendor shall achieve at least 80% of agreed monthly KPIs. Consistent failure (3+ consecutive months below 70%) shall constitute material breach and grounds for termination with a 30-day cure period.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c006-cl4',
        text: 'During the term, Client agrees not to engage any other digital marketing agency for services that overlap with the Services defined in Schedule A.',
        risk: 'medium',
        category: 'Exclusivity',
        explanation: 'Exclusivity clause prevents engaging other agencies even for services not adequately covered. This limits competitive flexibility.',
        negotiationLeverage: 'medium',
      },
    ],
    keyDates: [
      {
        label: 'Contract Expiry',
        date: '2026-10-31',
        daysRemaining: daysFrom('2026-10-31'),
        urgency: 'warning',
        type: 'expiry',
      },
      {
        label: 'Q3 Performance Review',
        date: '2026-08-01',
        daysRemaining: daysFrom('2026-08-01'),
        urgency: 'normal',
        type: 'milestone',
      },
    ],
    summary: {
      description: 'Twelve-month digital marketing retainer covering SEO, paid social, content creation, and email campaigns. Deliverables: 8 blog posts/month, monthly paid social management, quarterly strategy reviews.',
      termLength: '12 months (2025-11-01 to 2026-10-31)',
      keyObligations: [
        'Monthly retainer of €3,000 due on 1st of each month',
        'Client cannot terminate for convenience — only for uncured material breach',
        'Exclusive engagement — cannot hire competing agencies',
        'Monthly KPI review and reporting',
      ],
      biggestRisk: 'IP ownership vesting in Vendor means all content, campaigns, and brand assets are lost upon contract termination. Combined with one-sided termination clause, Client has minimal exit options.',
      recommendedAction: 'Immediately negotiate IP ownership transfer and mutual termination rights. These are non-standard clauses that place Client at extreme disadvantage. Engage legal counsel before next monthly payment.',
    },
    recurringObligations: [
      {
        id: 'c006-ro1',
        label: 'Monthly Retainer Payment',
        frequency: 'monthly',
        nextDue: '2026-07-01',
        description: 'Monthly marketing retainer of €3,000.',
      },
      {
        id: 'c006-ro2',
        label: 'Monthly KPI Report Review',
        frequency: 'monthly',
        nextDue: '2026-07-01',
        description: 'Review and approve monthly performance report against agreed KPIs.',
      },
    ],
  },

  // Contract 7: Payment Processor Agreement
  {
    id: 'c007',
    name: 'Payment Processing Agreement',
    counterparty: 'SwiftPay Europe BV',
    type: 'Service Contract',
    status: 'active',
    value: 3600,
    uploadDate: '2024-06-20',
    effectiveDate: '2024-07-01',
    expiryDate: '2028-06-30',
    riskScore: 68,
    riskBreakdown: [
      { category: 'Indemnification', count: 1, severity: 'high' },
      { category: 'Fee Changes', count: 1, severity: 'medium' },
      { category: 'Data Security', count: 1, severity: 'medium' },
      { category: 'Suspension Rights', count: 1, severity: 'medium' },
    ],
    clauses: [
      {
        id: 'c007-cl1',
        text: 'Merchant shall indemnify, defend, and hold SwiftPay harmless from any and all losses, liabilities, damages, costs, and expenses (including legal fees) arising from: (i) Merchant\'s breach of this Agreement; (ii) any fraud or chargebacks initiated by Merchant\'s customers; (iii) any regulatory fines or penalties related to Merchant\'s business operations; (iv) any third-party claims related to Merchant\'s products or services.',
        risk: 'critical',
        category: 'Indemnification',
        explanation: 'Extremely broad indemnification including customer chargebacks and regulatory fines. Third-party product liability claims can be substantial and are typically outside a merchant\'s ability to fully control.',
        suggestedRedline: 'Merchant indemnification shall be limited to claims arising from Merchant\'s gross negligence, willful misconduct, or material breach of this Agreement. Chargebacks shall be handled per the Chargeback Policy in Schedule B, with liability capped at the disputed transaction amount.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c007-cl2',
        text: 'SwiftPay may modify transaction fees, interchange rates, and service charges upon thirty (30) days email notice. Continued use of the service constitutes acceptance of revised fees.',
        risk: 'medium',
        category: 'Fee Changes',
        explanation: 'Unilateral fee modification with 30-day notice and passive acceptance is common in payment processing but worth monitoring. Current fee structure: 1.8% + €0.20 per transaction.',
        negotiationLeverage: 'low',
      },
      {
        id: 'c007-cl3',
        text: 'SwiftPay may immediately suspend Merchant\'s account and withhold funds if SwiftPay reasonably believes there is increased fraud risk, unusual transaction patterns, regulatory inquiry, or reputational risk to SwiftPay.',
        risk: 'medium',
        category: 'Suspension Rights',
        explanation: 'Broad suspension rights with subjective "reasonably believes" standard and no cure period before fund withholding creates operational risk.',
        negotiationLeverage: 'low',
      },
    ],
    keyDates: [
      {
        label: 'Contract Expiry',
        date: '2028-06-30',
        daysRemaining: daysFrom('2028-06-30'),
        urgency: 'normal',
        type: 'expiry',
      },
      {
        label: 'Annual Fee Review',
        date: '2026-07-01',
        daysRemaining: daysFrom('2026-07-01'),
        urgency: 'normal',
        type: 'milestone',
      },
    ],
    summary: {
      description: 'Four-year payment processing agreement with SwiftPay Europe. Covers card-present and card-not-present transactions, recurring billing, and multi-currency settlement.',
      termLength: '4 years (2024-07-01 to 2028-06-30)',
      keyObligations: [
        'Monthly minimum transaction volume of €5,000 or €50 minimum fee applies',
        'PCI-DSS compliance certification required annually',
        'Maintain chargeback ratio below 1%',
        'Notify SwiftPay of any business model changes within 10 days',
      ],
      biggestRisk: 'Broad indemnification includes customer chargebacks and regulatory fines, creating open-ended financial exposure that scales with transaction volume.',
      recommendedAction: 'Engage legal counsel to limit indemnification scope at next amendment cycle. Ensure PCI-DSS certification is current. Monitor chargeback ratios monthly.',
    },
    recurringObligations: [
      {
        id: 'c007-ro1',
        label: 'PCI-DSS Compliance Certification',
        frequency: 'annual',
        nextDue: '2026-07-01',
        description: 'Annual PCI-DSS self-assessment questionnaire and vulnerability scan required.',
      },
    ],
  },

  // Contract 8: Co-working Space
  {
    id: 'c008',
    name: 'Co-working Membership – Eixample Hub',
    counterparty: 'Eixample Creative Hub SCP',
    type: 'Lease',
    status: 'active',
    value: 9600,
    uploadDate: '2026-01-05',
    effectiveDate: '2026-01-01',
    expiryDate: '2026-07-31',
    riskScore: 22,
    riskBreakdown: [
      { category: 'Month-to-Month Terms', count: 1, severity: 'low' },
      { category: 'Access Rights', count: 1, severity: 'low' },
    ],
    clauses: [
      {
        id: 'c008-cl1',
        text: 'Membership shall continue on a month-to-month basis following the initial term. Either party may terminate upon thirty (30) days written notice. No penalty applies for termination after the initial term.',
        risk: 'low',
        category: 'Month-to-Month Terms',
        explanation: 'Flexible month-to-month terms with 30-day exit. Very favorable for tenant. Low risk.',
      },
      {
        id: 'c008-cl2',
        text: 'Member is granted access to shared workspace, meeting rooms (up to 8 hours/month), high-speed internet, printing facilities, and mail reception services.',
        risk: 'low',
        category: 'Access Rights',
        explanation: 'Standard co-working access rights. Meeting room cap of 8 hours/month may be insufficient for heavy use periods.',
      },
    ],
    keyDates: [
      {
        label: 'Initial Term End / Month-to-Month Start',
        date: '2026-07-31',
        daysRemaining: daysFrom('2026-07-31'),
        urgency: 'warning',
        type: 'renewal',
      },
    ],
    summary: {
      description: 'Shared co-working space membership for overflow and satellite team use. 4 dedicated desks in shared area of Eixample Creative Hub, Barcelona.',
      termLength: '7 months initial + month-to-month (from 2026-07-31)',
      keyObligations: [
        'Monthly membership fee of €800 due 1st of each month',
        'Meeting room usage capped at 8 hours/month',
        'No overnight equipment storage without prior authorization',
      ],
      biggestRisk: 'Low risk agreement. Month-to-month flexibility is favorable.',
      recommendedAction: 'Assess whether co-working space is still needed given Barcelona HQ lease. Could be terminated with 30-day notice if team consolidation occurs.',
    },
    recurringObligations: [
      {
        id: 'c008-ro1',
        label: 'Monthly Membership Fee',
        frequency: 'monthly',
        nextDue: '2026-07-01',
        description: 'Co-working membership fee of €800/month.',
      },
    ],
  },

  // Contract 9: Cloud Hosting Agreement
  {
    id: 'c009',
    name: 'Cloud Infrastructure Agreement – NimbusClouds',
    counterparty: 'NimbusClouds Europe GmbH',
    type: 'SaaS Subscription',
    status: 'active',
    value: 24000,
    uploadDate: '2025-03-28',
    effectiveDate: '2025-04-01',
    expiryDate: '2027-03-31',
    riskScore: 55,
    riskBreakdown: [
      { category: 'Data Ownership', count: 1, severity: 'medium' },
      { category: 'SLA & Uptime', count: 1, severity: 'medium' },
      { category: 'Price Escalation', count: 1, severity: 'medium' },
      { category: 'Data Location', count: 1, severity: 'low' },
    ],
    clauses: [
      {
        id: 'c009-cl1',
        text: 'NimbusClouds may access, process, and utilize Customer Data for purposes including service improvement, product development, and training of machine learning models, provided that such data is aggregated and anonymized. NimbusClouds claims no ownership over Customer Data in its identifiable form.',
        risk: 'medium',
        category: 'Data Ownership',
        explanation: '"Aggregated and anonymized" data use for ML training is ambiguous — re-identification is possible with modern AI. The carve-out for "identifiable form" is insufficient protection for proprietary contract data.',
        suggestedRedline: 'NimbusClouds may not use Customer Data for any purpose other than providing and maintaining the contracted Services. Customer retains full ownership of all Customer Data at all times. NimbusClouds may not use Customer Data for training ML models without explicit written consent.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c009-cl2',
        text: 'NimbusClouds guarantees 99.5% monthly uptime for core compute and storage services. Service credits shall be the sole remedy for downtime: 10% credit for availability between 99.0%-99.5%, 25% credit for availability below 99.0%.',
        risk: 'medium',
        category: 'SLA & Uptime',
        explanation: '99.5% uptime allows up to 3.65 hours downtime per month. Credits as sole remedy means no right to terminate even for extended outages.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c009-cl3',
        text: 'Annual pricing is subject to adjustment based on infrastructure cost indices. NimbusClouds will provide sixty (60) days notice of any price changes. Increases shall not exceed twelve percent (12%) in any twelve-month period.',
        risk: 'medium',
        category: 'Price Escalation',
        explanation: '12% annual cap is relatively high for infrastructure. At current €24,000/year, this could reach €26,880 next renewal.',
        suggestedRedline: 'Annual price adjustments shall not exceed the lesser of five percent (5%) or the EU HICP inflation rate for the prior year. Customer may terminate without penalty if the proposed increase exceeds this threshold.',
        negotiationLeverage: 'medium',
      },
    ],
    keyDates: [
      {
        label: 'Contract Expiry',
        date: '2027-03-31',
        daysRemaining: daysFrom('2027-03-31'),
        urgency: 'normal',
        type: 'expiry',
      },
      {
        label: 'Annual Price Review',
        date: '2026-04-01',
        daysRemaining: daysFrom('2026-04-01'),
        urgency: 'normal',
        type: 'milestone',
      },
    ],
    summary: {
      description: 'Two-year cloud infrastructure agreement for compute, storage, and CDN services. Includes dedicated EU-West region deployment, 24/7 support, and managed backup.',
      termLength: '2 years (2025-04-01 to 2027-03-31)',
      keyObligations: [
        'Annual commitment of €24,000 — monthly usage billed against commitment',
        'Notify NimbusClouds of security incidents within 72 hours',
        'Comply with Acceptable Use Policy',
        'Maintain valid billing information',
      ],
      biggestRisk: 'Data ownership ambiguity around ML training use of contract data. If ContractWatch stores client contracts in the cloud, this clause may allow vendor to learn from that data.',
      recommendedAction: 'Request explicit DPA amendment prohibiting ML training on Customer Data. Evaluate data encryption and segregation practices. Review at 2027 renewal.',
    },
    recurringObligations: [
      {
        id: 'c009-ro1',
        label: 'Monthly Usage Reconciliation',
        frequency: 'monthly',
        nextDue: '2026-07-01',
        description: 'Monthly review of cloud usage vs. committed spend to avoid overage charges.',
      },
    ],
  },

  // Contract 10: Contractor Agreement
  {
    id: 'c010',
    name: 'Subcontractor Agreement – Backend Development',
    counterparty: 'Ramos & Vega Tecnología SL',
    type: 'Service Contract',
    status: 'active',
    value: 28800,
    uploadDate: '2025-12-01',
    effectiveDate: '2025-12-01',
    expiryDate: '2026-11-30',
    riskScore: 77,
    riskBreakdown: [
      { category: 'IP Ownership', count: 1, severity: 'high' },
      { category: 'Non-Solicitation', count: 1, severity: 'high' },
      { category: 'Warranties', count: 1, severity: 'medium' },
      { category: 'Audit Rights', count: 1, severity: 'low' },
    ],
    clauses: [
      {
        id: 'c010-cl1',
        text: 'Contractor retains all intellectual property rights to code, algorithms, architectures, and methodologies developed during the engagement, and grants Client a non-exclusive, non-transferable license to use the Deliverables solely for Client\'s internal business purposes.',
        risk: 'critical',
        category: 'IP Ownership',
        explanation: 'Contractor retaining IP ownership of custom-developed code is a critical risk. This means the company does not own its own product\'s codebase. The non-exclusive license could be revoked or expire.',
        suggestedRedline: 'All Deliverables created specifically for Client under this Agreement shall be works-for-hire and all intellectual property rights therein shall vest exclusively in Client upon full payment of applicable fees. Contractor retains rights to pre-existing tools, open-source components, and general know-how.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c010-cl2',
        text: 'For a period of twenty-four (24) months following termination, Client shall not directly or indirectly solicit, hire, or engage any employee or contractor of Vendor who performed Services under this Agreement.',
        risk: 'critical',
        category: 'Non-Solicitation',
        explanation: '24-month non-solicitation is longer than standard (typically 12 months) and could prevent hiring key engineering talent discovered through this engagement.',
        suggestedRedline: 'For a period of twelve (12) months following termination, neither party shall directly solicit the employees of the other party who were directly involved in this engagement. This clause does not prevent responses to general public job postings.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c010-cl3',
        text: 'Contractor warrants that Deliverables will substantially conform to agreed specifications for a period of thirty (30) days following delivery. After this warranty period, all support and maintenance shall be subject to separate agreement at Contractor\'s then-current rates.',
        risk: 'medium',
        category: 'Warranties',
        explanation: '30-day warranty period is insufficient for complex software. Industry standard is 90-180 days for enterprise software deliverables.',
        suggestedRedline: 'Contractor warrants that Deliverables will substantially conform to agreed specifications for a period of ninety (90) days following written acceptance. During the warranty period, Contractor shall remedy any non-conformance at no additional cost.',
        negotiationLeverage: 'medium',
      },
    ],
    keyDates: [
      {
        label: 'Contract Expiry',
        date: '2026-11-30',
        daysRemaining: daysFrom('2026-11-30'),
        urgency: 'warning',
        type: 'expiry',
      },
      {
        label: 'Q3 Milestone Delivery',
        date: '2026-09-01',
        daysRemaining: daysFrom('2026-09-01'),
        urgency: 'normal',
        type: 'milestone',
      },
    ],
    summary: {
      description: 'Twelve-month backend development subcontractor agreement. Scope: API development, database architecture, and third-party integrations for ContractWatch platform.',
      termLength: '12 months (2025-12-01 to 2026-11-30)',
      keyObligations: [
        'Monthly retainer of €2,400 for 60 hours/month',
        'Deliverables as specified in attached Statement of Work',
        '24-month non-solicitation of Contractor employees post-termination',
        'Weekly progress reports and bi-weekly code reviews',
      ],
      biggestRisk: 'IP ownership clause means ContractWatch does not own the code being built. If the relationship ends, the company may be unable to modify, redistribute, or relicense its own product.',
      recommendedAction: 'Negotiate IP ownership transfer as highest priority. This is a fundamental term that should be corrected before additional development work is commissioned.',
    },
    recurringObligations: [
      {
        id: 'c010-ro1',
        label: 'Monthly Development Retainer',
        frequency: 'monthly',
        nextDue: '2026-07-01',
        description: 'Monthly retainer of €2,400 for 60 hours of backend development.',
      },
      {
        id: 'c010-ro2',
        label: 'Quarterly Code Audit',
        frequency: 'quarterly',
        nextDue: '2026-09-01',
        description: 'Quarterly code quality and security audit of all deliverables.',
      },
    ],
  },

  // Contract 11: Business Liability Insurance
  {
    id: 'c011',
    name: 'Business Liability Insurance Policy',
    counterparty: 'EuroShield Insurance SA',
    type: 'Insurance',
    status: 'expiring_soon',
    value: 5200,
    uploadDate: '2025-07-01',
    effectiveDate: '2025-07-10',
    expiryDate: '2026-07-10',
    riskScore: 61,
    riskBreakdown: [
      { category: 'Policy Exclusions', count: 1, severity: 'high' },
      { category: 'Claims Process', count: 1, severity: 'medium' },
      { category: 'Coverage Limits', count: 1, severity: 'medium' },
    ],
    clauses: [
      {
        id: 'c011-cl1',
        text: 'This Policy does not cover: (a) claims arising from intentional acts, willful misconduct, or fraud; (b) losses resulting from cyberattacks, data breaches, ransomware, or unauthorized system access; (c) claims arising from the rendering of or failure to render professional advice; (d) losses resulting from contractual liability assumed in excess of applicable law; (e) fines, penalties, and punitive damages.',
        risk: 'critical',
        category: 'Policy Exclusions',
        explanation: 'Critical gap: Cyber exclusion means no coverage for data breaches or ransomware — a significant exposure for a SaaS contract intelligence platform. Professional advice exclusion may also exclude technology E&O claims.',
        suggestedRedline: 'Review and obtain separate Cyber Liability Insurance policy with minimum €1M coverage. Evaluate Professional Indemnity / E&O coverage as separate policy.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c011-cl2',
        text: 'Claims must be reported to EuroShield within thirty (30) days of the Insured first becoming aware of a potential claim. Failure to report within this window may result in partial or total denial of coverage.',
        risk: 'medium',
        category: 'Claims Process',
        explanation: '30-day reporting window is strict. Ensure all team members know to escalate any potential claim indicators immediately.',
      },
      {
        id: 'c011-cl3',
        text: 'General liability coverage limit: €1,000,000 per occurrence / €2,000,000 aggregate. Product liability: €500,000 per occurrence. Employer\'s liability: €250,000 per employee.',
        risk: 'medium',
        category: 'Coverage Limits',
        explanation: 'Coverage limits are adequate for current business size. Review as company scales beyond 20 employees or €5M revenue.',
      },
    ],
    keyDates: [
      {
        label: 'CRITICAL: Policy Expiry',
        date: '2026-07-10',
        daysRemaining: daysFrom('2026-07-10'),
        urgency: 'critical',
        type: 'expiry',
      },
      {
        label: 'Renewal Premium Due',
        date: '2026-07-01',
        daysRemaining: daysFrom('2026-07-01'),
        urgency: 'critical',
        noticeRequired: 30,
        actionDeadline: '2026-07-01',
        type: 'payment',
      },
    ],
    summary: {
      description: 'Annual business liability insurance covering general liability, product liability, and employer\'s liability. Policy number ERS-2025-BCN-0441.',
      termLength: '12 months (2025-07-10 to 2026-07-10)',
      keyObligations: [
        'Annual premium of €5,200 due upon renewal',
        'Report potential claims within 30 days of awareness',
        'Notify EuroShield of significant business changes (acquisitions, new product lines)',
        'Maintain accurate employee count records',
      ],
      biggestRisk: 'Policy expires July 10, 2026 — 24 days away — with no cyber coverage. The company is completely uninsured for data breaches and ransomware attacks, which are the most likely risk vectors for a SaaS platform.',
      recommendedAction: 'URGENT: Renew policy immediately and simultaneously obtain Cyber Liability and Professional Indemnity coverage. Risk of operating without business insurance within 24 days.',
    },
    recurringObligations: [
      {
        id: 'c011-ro1',
        label: 'Annual Premium Payment',
        frequency: 'annual',
        nextDue: '2026-07-01',
        description: 'Annual insurance premium renewal of approximately €5,200.',
      },
    ],
  },

  // Contract 12: Non-Compete Agreement
  {
    id: 'c012',
    name: 'Non-Compete Agreement – Former CTO',
    counterparty: 'Marcus Bauer (Individual)',
    type: 'Employment',
    status: 'active',
    value: 0,
    uploadDate: '2025-10-01',
    effectiveDate: '2025-10-01',
    expiryDate: '2027-09-30',
    riskScore: 84,
    riskBreakdown: [
      { category: 'Non-Compete Scope', count: 1, severity: 'high' },
      { category: 'Geographic Reach', count: 1, severity: 'high' },
      { category: 'Enforceability', count: 1, severity: 'high' },
      { category: 'Consideration', count: 1, severity: 'medium' },
    ],
    clauses: [
      {
        id: 'c012-cl1',
        text: 'Employee agrees that for a period of twenty-four (24) months following the Separation Date, Employee shall not, directly or indirectly, engage in, be employed by, consult for, own, manage, operate, or control any business engaged in the development, marketing, or sale of contract management software, legal technology, or document intelligence solutions anywhere in the European Union, United Kingdom, or North America.',
        risk: 'critical',
        category: 'Non-Compete Scope & Geography',
        explanation: 'A 24-month EU-wide non-compete covering legal tech broadly is almost certainly unenforceable under Spanish law (Art. 21 ET limits to 6 months for non-technical and 2 years for technical employees with adequate compensation) and may violate EU competition law. If unenforceable, the company has no protection.',
        suggestedRedline: 'Employee agrees, for a period of twelve (12) months following the Separation Date, not to directly compete with Company by working for or founding companies offering substantially identical contract intelligence products in Spain and Portugal, provided Company continues paying Employee\'s final base salary during this period.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c012-cl2',
        text: 'Employee shall not, for a period of twenty-four (24) months following the Separation Date, solicit or attempt to solicit any customers, prospective customers, or business partners of the Company whom Employee had material contact with during the twelve (12) months prior to the Separation Date.',
        risk: 'critical',
        category: 'Non-Solicitation – Customers',
        explanation: 'Non-solicitation scope is broad but more defensible than the non-compete. 24 months is on the longer end — 12 months is more standard and enforceable.',
        suggestedRedline: 'Employee shall not, for twelve (12) months following the Separation Date, directly solicit customers with whom Employee had primary account responsibility in the six (6) months prior to separation.',
        negotiationLeverage: 'medium',
      },
      {
        id: 'c012-cl3',
        text: 'As consideration for this Agreement, Company paid Employee a one-time lump sum of €5,000 upon execution.',
        risk: 'critical',
        category: 'Consideration Adequacy',
        explanation: '€5,000 one-time payment as consideration for a 24-month EU-wide non-compete is likely inadequate under Spanish employment law, which typically requires compensation proportional to the restriction imposed. Courts may void the agreement for lack of adequate consideration.',
        suggestedRedline: 'As consideration, Company shall pay Employee 50% of Employee\'s final annual base salary (€[X]) distributed monthly over the 24-month non-compete period. Employee may waive the non-compete by returning any received consideration.',
        negotiationLeverage: 'high',
      },
      {
        id: 'c012-cl4',
        text: 'This Agreement shall be governed by Spanish law. Any disputes shall be submitted to mandatory arbitration in Madrid, Spain.',
        risk: 'medium',
        category: 'Governing Law',
        explanation: 'Spanish law governing is appropriate. Mandatory arbitration limits litigation costs but also limits enforceability remedies in some circumstances.',
      },
    ],
    keyDates: [
      {
        label: 'Non-Compete Expiry',
        date: '2027-09-30',
        daysRemaining: daysFrom('2027-09-30'),
        urgency: 'normal',
        type: 'expiry',
      },
      {
        label: '12-Month Review',
        date: '2026-10-01',
        daysRemaining: daysFrom('2026-10-01'),
        urgency: 'warning',
        type: 'milestone',
      },
    ],
    summary: {
      description: 'Post-employment non-compete and non-solicitation agreement with former Chief Technology Officer Marcus Bauer, signed upon his departure on October 1, 2025.',
      termLength: '24 months (2025-10-01 to 2027-09-30)',
      keyObligations: [
        'Former employee prohibited from competing in legal tech / contract management across EU, UK, North America',
        'Non-solicitation of customers for 24 months',
        'Company paid one-time €5,000 consideration',
      ],
      biggestRisk: 'Agreement is likely unenforceable under Spanish employment law due to: (1) excessive geographic scope, (2) inadequate consideration, and (3) duration possibly exceeding statutory limits. If former CTO joins competitor, enforcement may fail in court.',
      recommendedAction: 'Engage Spanish employment law counsel immediately to assess enforceability. Consider negotiating a revised, compliant agreement with adequate compensation if the former CTO is at risk of joining a competitor.',
    },
    recurringObligations: [],
  },
]

export default mockContracts
